stages:
  - deploy

deploy:
  stage: deploy
  image: ruby:latest
  tags:
    - dalfcs_docker_kvm   
  before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
  script:
    - cd frontend
    - dpl --provider=heroku --app=$TUTORLY_HEROKU_APP_NAME --api-key=$HEROKU_API_KEY --cleanup
  only:
    - main
